/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.33.0
  Forc version: 0.35.3
  Fuel-Core version: 0.17.3
*/

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from 'fuels';

interface ContractAbiInterface extends Interface {
  functions: {
    hatch: FunctionFragment;
    new_swaygotchi: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'hatch', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'new_swaygotchi', values: [BigNumberish]): Uint8Array;

  decodeFunctionData(functionFragment: 'hatch', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'new_swaygotchi', data: BytesLike): DecodedValue;
}

export class ContractAbi extends Contract {
  interface: ContractAbiInterface;
  functions: {
    hatch: InvokeFunction<[age: BigNumberish], void>;
    new_swaygotchi: InvokeFunction<[age: BigNumberish], void>;
  };
}
